name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"

concurrency:
  # Cancel previous builds if a new one is triggered.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tests:
    name: ${{ matrix.os }}, py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest # disable because it's too slow
          - macos-14
        python-version: ["310", "311", "312", "313"]

    env:
      PIXI_ENV_NAME: test-py${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: ${{ env.PIXI_ENV_NAME }}
          activate-environment: true

      - name: Build and install package
        run: pixi install --environment ${{ env.PIXI_ENV_NAME }}

      - name: Run tests
        run: pixi run --environment ${{ env.PIXI_ENV_NAME }} test
